{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "duty_bot.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "duty_bot.name" . }}
    chart: {{ template "duty_bot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "duty_bot.fullname" . }}-postgres-service
  selector:
    matchLabels:
      app: {{ template "duty_bot.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.postgres.replicaCount }}
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: {{ template "duty_bot.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: postgresql-db
          image: postgres:16.3-bullseye
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | default "postgres" }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | default "postgres" }}
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | default "postgres" }}
          ports:
            - name: http
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
{{- end }}